[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma migrate deploy && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
